### ISSUE TITLE
Desync detection appears to compare the checksum of predicted frames to confirmed frames

### ISSUE THREAD

**Issue by nezuo** [gschup/bevy_ggrs#71] opened 2023-10-16 18:07 UTC
**Describe the bug**
Desyncs are reported because predicated checksums and confirmed checksums are being compared.

**To Reproduce**
My repro can be found here on the `desync-detection-issue` branch: <https://github.com/gschup/bevy_ggrs/compare/main...nezuo:bevy_ggrs:desync-detection-issue?expand=1>

I used clumsy so that it predicts inputs/rollbacks.

**Expected behavior**
Only the checksums of confirmed frames should be compared.

**Screenshots**
Frame 18s for player 1 (in order):
![image](https://github.com/gschup/bevy_ggrs/assets/48431591/ae2735c0-b100-4f08-b9d4-060d34c2c60d)
![image](https://github.com/gschup/bevy_ggrs/assets/48431591/17bac232-1657-461b-aeed-bbfe353390d5)

Frame 18 for player 2:
![image](https://github.com/gschup/bevy_ggrs/assets/48431591/eba05192-68fe-4626-9fde-4437058f6027)

The second frame 18 for player 1 is the same as player 2's frame 18. However, it's comparing the first frame 18 with player 2's frame 18.

**Comment by PraxTube** [comment] 2023-10-18 07:38
Yeah, checksums as they are right now only work when there is no ping
(or the ping is lower then the input delay), which is almost only the case
when testing locally.

However when testing with high ping you get desyncs non-stop
because the receiving client is constantly mispredicting and we have to rollback a bunch.

Comparing the checksum of only confirmed frames would fix this?

**Comment by johanhelsing** [comment] 2023-10-18 08:16
Thanks for taking the time looking into this! It does indeed not happen if input latency is higher than ping.

I didn't catch this earlier, since my game breaks on rollbacks due to the regression #63

**Comment by johanhelsing** [comment] 2023-10-20 11:36
This is bug in `ggrs`. I created a bug and a fix for it there (see referenced issues above)

**Comment by gschup** [comment] 2023-10-23 08:10
The fix is now merged in the ggrs repo, so the issue can be closed here, as well! (unless I am missing something)

**Comment by johanhelsing** [comment] 2023-10-23 08:12
Just wondering if it's good to keep it open until at least the main branch of this repo depends on a ggrs version that works (just for visibility in case this is tripping people up)

**Comment by gschup** [comment] 2023-10-23 08:16
You are right. I was under the impression that the main branch of this repo depends on the main branch of ggrs. At least that was my original intention in the past. It must have slipped through my fingers that we don't do that currently.

**Comment by gschup** [comment] 2023-10-26 06:36
this repo now depends on ggrs main, which should fix this issue.

**Closed by gschup** 2023-10-26 06:36 UTC
Labels: bug
